//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  empreendimentos: Empreendimentos;
  empreendimentosConnection: EmpreendimentosConnection;
  sobre: Sobre;
  sobreConnection: SobreConnection;
  contato: Contato;
  contatoConnection: ContatoConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryEmpreendimentosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEmpreendimentosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EmpreendimentosFilter>;
};


export type QuerySobreArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySobreConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SobreFilter>;
};


export type QueryContatoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContatoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContatoFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  empreendimentos?: InputMaybe<EmpreendimentosFilter>;
  sobre?: InputMaybe<SobreFilter>;
  contato?: InputMaybe<ContatoFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Empreendimentos | Sobre | Contato | Folder;

export type Home = Node & Document & {
  __typename?: 'Home';
  hero_titulo?: Maybe<Scalars['String']['output']>;
  hero_subtitulo?: Maybe<Scalars['String']['output']>;
  diferenciais_titulo?: Maybe<Scalars['String']['output']>;
  cta_titulo?: Maybe<Scalars['String']['output']>;
  cta_descricao?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeFilter = {
  hero_titulo?: InputMaybe<StringFilter>;
  hero_subtitulo?: InputMaybe<StringFilter>;
  diferenciais_titulo?: InputMaybe<StringFilter>;
  cta_titulo?: InputMaybe<StringFilter>;
  cta_descricao?: InputMaybe<StringFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type Empreendimentos = Node & Document & {
  __typename?: 'Empreendimentos';
  nome: Scalars['String']['output'];
  tipo?: Maybe<Scalars['String']['output']>;
  status?: Maybe<Scalars['String']['output']>;
  caixa?: Maybe<Scalars['Boolean']['output']>;
  imagem?: Maybe<Scalars['String']['output']>;
  descricao?: Maybe<Scalars['String']['output']>;
  destaques?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type EmpreendimentosFilter = {
  nome?: InputMaybe<StringFilter>;
  tipo?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  caixa?: InputMaybe<BooleanFilter>;
  imagem?: InputMaybe<ImageFilter>;
  descricao?: InputMaybe<StringFilter>;
  destaques?: InputMaybe<StringFilter>;
};

export type EmpreendimentosConnectionEdges = {
  __typename?: 'EmpreendimentosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Empreendimentos>;
};

export type EmpreendimentosConnection = Connection & {
  __typename?: 'EmpreendimentosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EmpreendimentosConnectionEdges>>>;
};

export type Sobre = Node & Document & {
  __typename?: 'Sobre';
  historia_titulo?: Maybe<Scalars['String']['output']>;
  historia_texto1?: Maybe<Scalars['String']['output']>;
  historia_texto2?: Maybe<Scalars['String']['output']>;
  fundador_bio1?: Maybe<Scalars['String']['output']>;
  fundador_bio2?: Maybe<Scalars['String']['output']>;
  fundador_quote?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SobreFilter = {
  historia_titulo?: InputMaybe<StringFilter>;
  historia_texto1?: InputMaybe<StringFilter>;
  historia_texto2?: InputMaybe<StringFilter>;
  fundador_bio1?: InputMaybe<StringFilter>;
  fundador_bio2?: InputMaybe<StringFilter>;
  fundador_quote?: InputMaybe<StringFilter>;
};

export type SobreConnectionEdges = {
  __typename?: 'SobreConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Sobre>;
};

export type SobreConnection = Connection & {
  __typename?: 'SobreConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SobreConnectionEdges>>>;
};

export type Contato = Node & Document & {
  __typename?: 'Contato';
  endereco?: Maybe<Scalars['String']['output']>;
  telefone?: Maybe<Scalars['String']['output']>;
  horario?: Maybe<Scalars['String']['output']>;
  whatsapp?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContatoFilter = {
  endereco?: InputMaybe<StringFilter>;
  telefone?: InputMaybe<StringFilter>;
  horario?: InputMaybe<StringFilter>;
  whatsapp?: InputMaybe<StringFilter>;
};

export type ContatoConnectionEdges = {
  __typename?: 'ContatoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contato>;
};

export type ContatoConnection = Connection & {
  __typename?: 'ContatoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContatoConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateEmpreendimentos: Empreendimentos;
  createEmpreendimentos: Empreendimentos;
  updateSobre: Sobre;
  createSobre: Sobre;
  updateContato: Contato;
  createContato: Contato;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateEmpreendimentosArgs = {
  relativePath: Scalars['String']['input'];
  params: EmpreendimentosMutation;
};


export type MutationCreateEmpreendimentosArgs = {
  relativePath: Scalars['String']['input'];
  params: EmpreendimentosMutation;
};


export type MutationUpdateSobreArgs = {
  relativePath: Scalars['String']['input'];
  params: SobreMutation;
};


export type MutationCreateSobreArgs = {
  relativePath: Scalars['String']['input'];
  params: SobreMutation;
};


export type MutationUpdateContatoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContatoMutation;
};


export type MutationCreateContatoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContatoMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  empreendimentos?: InputMaybe<EmpreendimentosMutation>;
  sobre?: InputMaybe<SobreMutation>;
  contato?: InputMaybe<ContatoMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  empreendimentos?: InputMaybe<EmpreendimentosMutation>;
  sobre?: InputMaybe<SobreMutation>;
  contato?: InputMaybe<ContatoMutation>;
};

export type HomeMutation = {
  hero_titulo?: InputMaybe<Scalars['String']['input']>;
  hero_subtitulo?: InputMaybe<Scalars['String']['input']>;
  diferenciais_titulo?: InputMaybe<Scalars['String']['input']>;
  cta_titulo?: InputMaybe<Scalars['String']['input']>;
  cta_descricao?: InputMaybe<Scalars['String']['input']>;
};

export type EmpreendimentosMutation = {
  nome?: InputMaybe<Scalars['String']['input']>;
  tipo?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  caixa?: InputMaybe<Scalars['Boolean']['input']>;
  imagem?: InputMaybe<Scalars['String']['input']>;
  descricao?: InputMaybe<Scalars['String']['input']>;
  destaques?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SobreMutation = {
  historia_titulo?: InputMaybe<Scalars['String']['input']>;
  historia_texto1?: InputMaybe<Scalars['String']['input']>;
  historia_texto2?: InputMaybe<Scalars['String']['input']>;
  fundador_bio1?: InputMaybe<Scalars['String']['input']>;
  fundador_bio2?: InputMaybe<Scalars['String']['input']>;
  fundador_quote?: InputMaybe<Scalars['String']['input']>;
};

export type ContatoMutation = {
  endereco?: InputMaybe<Scalars['String']['input']>;
  telefone?: InputMaybe<Scalars['String']['input']>;
  horario?: InputMaybe<Scalars['String']['input']>;
  whatsapp?: InputMaybe<Scalars['String']['input']>;
};

export type HomePartsFragment = { __typename: 'Home', hero_titulo?: string | null, hero_subtitulo?: string | null, diferenciais_titulo?: string | null, cta_titulo?: string | null, cta_descricao?: string | null };

export type EmpreendimentosPartsFragment = { __typename: 'Empreendimentos', nome: string, tipo?: string | null, status?: string | null, caixa?: boolean | null, imagem?: string | null, descricao?: string | null, destaques?: Array<string | null> | null };

export type SobrePartsFragment = { __typename: 'Sobre', historia_titulo?: string | null, historia_texto1?: string | null, historia_texto2?: string | null, fundador_bio1?: string | null, fundador_bio2?: string | null, fundador_quote?: string | null };

export type ContatoPartsFragment = { __typename: 'Contato', endereco?: string | null, telefone?: string | null, horario?: string | null, whatsapp?: string | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, hero_titulo?: string | null, hero_subtitulo?: string | null, diferenciais_titulo?: string | null, cta_titulo?: string | null, cta_descricao?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, hero_titulo?: string | null, hero_subtitulo?: string | null, diferenciais_titulo?: string | null, cta_titulo?: string | null, cta_descricao?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type EmpreendimentosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EmpreendimentosQuery = { __typename?: 'Query', empreendimentos: { __typename: 'Empreendimentos', id: string, nome: string, tipo?: string | null, status?: string | null, caixa?: boolean | null, imagem?: string | null, descricao?: string | null, destaques?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EmpreendimentosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EmpreendimentosFilter>;
}>;


export type EmpreendimentosConnectionQuery = { __typename?: 'Query', empreendimentosConnection: { __typename?: 'EmpreendimentosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EmpreendimentosConnectionEdges', cursor: string, node?: { __typename: 'Empreendimentos', id: string, nome: string, tipo?: string | null, status?: string | null, caixa?: boolean | null, imagem?: string | null, descricao?: string | null, destaques?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SobreQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SobreQuery = { __typename?: 'Query', sobre: { __typename: 'Sobre', id: string, historia_titulo?: string | null, historia_texto1?: string | null, historia_texto2?: string | null, fundador_bio1?: string | null, fundador_bio2?: string | null, fundador_quote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SobreConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SobreFilter>;
}>;


export type SobreConnectionQuery = { __typename?: 'Query', sobreConnection: { __typename?: 'SobreConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SobreConnectionEdges', cursor: string, node?: { __typename: 'Sobre', id: string, historia_titulo?: string | null, historia_texto1?: string | null, historia_texto2?: string | null, fundador_bio1?: string | null, fundador_bio2?: string | null, fundador_quote?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ContatoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContatoQuery = { __typename?: 'Query', contato: { __typename: 'Contato', id: string, endereco?: string | null, telefone?: string | null, horario?: string | null, whatsapp?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContatoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContatoFilter>;
}>;


export type ContatoConnectionQuery = { __typename?: 'Query', contatoConnection: { __typename?: 'ContatoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContatoConnectionEdges', cursor: string, node?: { __typename: 'Contato', id: string, endereco?: string | null, telefone?: string | null, horario?: string | null, whatsapp?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  hero_titulo
  hero_subtitulo
  diferenciais_titulo
  cta_titulo
  cta_descricao
}
    `;
export const EmpreendimentosPartsFragmentDoc = gql`
    fragment EmpreendimentosParts on Empreendimentos {
  __typename
  nome
  tipo
  status
  caixa
  imagem
  descricao
  destaques
}
    `;
export const SobrePartsFragmentDoc = gql`
    fragment SobreParts on Sobre {
  __typename
  historia_titulo
  historia_texto1
  historia_texto2
  fundador_bio1
  fundador_bio2
  fundador_quote
}
    `;
export const ContatoPartsFragmentDoc = gql`
    fragment ContatoParts on Contato {
  __typename
  endereco
  telefone
  horario
  whatsapp
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const EmpreendimentosDocument = gql`
    query empreendimentos($relativePath: String!) {
  empreendimentos(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EmpreendimentosParts
  }
}
    ${EmpreendimentosPartsFragmentDoc}`;
export const EmpreendimentosConnectionDocument = gql`
    query empreendimentosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EmpreendimentosFilter) {
  empreendimentosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EmpreendimentosParts
      }
    }
  }
}
    ${EmpreendimentosPartsFragmentDoc}`;
export const SobreDocument = gql`
    query sobre($relativePath: String!) {
  sobre(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SobreParts
  }
}
    ${SobrePartsFragmentDoc}`;
export const SobreConnectionDocument = gql`
    query sobreConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SobreFilter) {
  sobreConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SobreParts
      }
    }
  }
}
    ${SobrePartsFragmentDoc}`;
export const ContatoDocument = gql`
    query contato($relativePath: String!) {
  contato(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContatoParts
  }
}
    ${ContatoPartsFragmentDoc}`;
export const ContatoConnectionDocument = gql`
    query contatoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContatoFilter) {
  contatoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContatoParts
      }
    }
  }
}
    ${ContatoPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    empreendimentos(variables: EmpreendimentosQueryVariables, options?: C): Promise<{data: EmpreendimentosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EmpreendimentosQueryVariables, query: string}> {
        return requester<{data: EmpreendimentosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EmpreendimentosQueryVariables, query: string}, EmpreendimentosQueryVariables>(EmpreendimentosDocument, variables, options);
      },
    empreendimentosConnection(variables?: EmpreendimentosConnectionQueryVariables, options?: C): Promise<{data: EmpreendimentosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EmpreendimentosConnectionQueryVariables, query: string}> {
        return requester<{data: EmpreendimentosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EmpreendimentosConnectionQueryVariables, query: string}, EmpreendimentosConnectionQueryVariables>(EmpreendimentosConnectionDocument, variables, options);
      },
    sobre(variables: SobreQueryVariables, options?: C): Promise<{data: SobreQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SobreQueryVariables, query: string}> {
        return requester<{data: SobreQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SobreQueryVariables, query: string}, SobreQueryVariables>(SobreDocument, variables, options);
      },
    sobreConnection(variables?: SobreConnectionQueryVariables, options?: C): Promise<{data: SobreConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SobreConnectionQueryVariables, query: string}> {
        return requester<{data: SobreConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SobreConnectionQueryVariables, query: string}, SobreConnectionQueryVariables>(SobreConnectionDocument, variables, options);
      },
    contato(variables: ContatoQueryVariables, options?: C): Promise<{data: ContatoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContatoQueryVariables, query: string}> {
        return requester<{data: ContatoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContatoQueryVariables, query: string}, ContatoQueryVariables>(ContatoDocument, variables, options);
      },
    contatoConnection(variables?: ContatoConnectionQueryVariables, options?: C): Promise<{data: ContatoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContatoConnectionQueryVariables, query: string}> {
        return requester<{data: ContatoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContatoConnectionQueryVariables, query: string}, ContatoConnectionQueryVariables>(ContatoConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  